name: 'Update kerbalChangelog'
description: 'Update kerbalChangelog'
inputs:
  path:
    description: 'path to readme'
    required: true
  version:
    description: 'tag of release'
    required: true
  body:
    description: 'body of release'
    required: true
runs:
  using: "composite"
  steps:
    - name: check out this repo
      uses: actions/checkout@v3
      with:
        repository: StonesmileGit/BuildTools
        path: ./BuildTools/

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.0

    - name: Make metadata
      run: python ${GITHUB_WORKSPACE}/BuildTools/processChangeLog.py ${{ inputs.version }} ${{ inputs.body }} ${{ inputs.path }}
      shell: bash
