name: 'Update kerbalChangelog'
description: 'Update kerbalChangelog'
inputs:
  path:
    description: 'path to readme'
    required: true
  tag:
    description: 'tag of release'
    required: true
  body:
    description: 'body of release'
    required: true
runs:
  using: "composite"
  steps:
    - name: check out BuildTools
      uses: KSP-RO/BuildTools/checkout-BuildTools@master

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.0

    - name: Process changelog
      shell: bash
      run: |
        body=$(cat <<EOF
        ${{ inputs.body }}'
        EOF
        )
        echo "$body"
        python ${GITHUB_WORKSPACE}/BuildTools/process-changelog/processChangeLog.py ${{ inputs.tag }} "$body" ${{ inputs.path }}
