name: 'Remove excess DLLs'
description: 'MSBuild has a bug where private or non-copylocal DLLs get copied anyway'
inputs:
  path:
    description: 'path to DLL files'
    required: true
runs:
  using: "composite"
  steps:
    - name: delete dlls
      shell: bash {0}
      run: |
        find ${{ inputs.path }} -type f -name "System.dll" -delete
        find ${{ inputs.path }} -type f -name "System.Xml.dll" -delete
        find ${{ inputs.path }} -type f -name "System.Core.dll" -delete
        # purely so last exit code is 0
        ls
