name: 'Update assemblyInfo'
description: 'Update assemblyInfo file using tag'
inputs:
  path:
    description: 'path to assemblyInfo'
    required: true
  tag:
    description: 'tag of release'
    required: true
  informational-version:
    description: 'text to put in the AssemblyInformationalVersion'
    required: false

runs:
  using: "composite"
  steps:
    - name: update assemblyInfo
      shell: bash
      env:
        TAG_STRING: ${{ inputs.tag }}
      run: |
        VFULL="$(echo $TAG_STRING | sed -e s/v//)"
        VMAJOR="$(echo $VFULL | cut -f 1 -d '.')"
        VMINOR="$(echo $VFULL | cut -f 2 -d '.')"
        VPATCH="$(echo $VFULL | cut -f 3 -d '.')"
        VBUILD="$(echo $VFULL | cut -f 4 -d '.')"
        ASSEMBLYINFORMATIONALVERSION="${{ inputs.informational-version}}"

        echo "Version string: $TAG_STRING"
        echo "Version is $VMAJOR dot $VMINOR dot $VPATCH dot $VBUILD"
        sed \
          -e "s/CIBUILD_disabled/CIBUILD/" \
          -e "s/@MAJOR@/$VMAJOR/" \
          -e "s/@MINOR@/$VMINOR/" \
          -e "s/@PATCH@/$VPATCH/" \
          -e "s/@BUILD@/$VBUILD/" \
          -i ${{ inputs.path }}
        [ -n "$ASSEMBLYINFORMATIONALVERSION" ] && \
          sed \
            -e "s/@ASSEMBLYINFORMATIONALVERSION@/$ASSEMBLYINFORMATIONALVERSION/" \
            -i ${{ inputs.path }}

        grep CIBUILD ${{ inputs.path }}
        grep AssemblyFileVersion ${{ inputs.path }}
