name: 'Update Version File'
description: 'Update version file using regex'
inputs:
  path:
    description: 'path to .version file'
    required: true
  tag:
    description: 'tag of release'
    required: true
runs:
  using: "composite"
  steps:
    - name: check out BuildTools
      uses: KSP-RO/BuildTools/checkout-BuildTools@master

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3

    - name: Update readme
      shell: bash
      run: python ${GITHUB_WORKSPACE}/BuildTools/update-version-file/makeMeta.py ${{ inputs.tag }} ${{ inputs.path }}
