name: Check Secret

on:
  workflow_call:
    secrets:
      KSP_ZIP_PASSWORD:
        required: true
    outputs:
      has-password:
        value: ${{ jobs.check-secret.has-password.outputs.defined }}

jobs:
  check-secret:
    name: Check Secret
    runs-on: ubuntu-latest
    steps:
      - id: has-password
        if: "${{ env.KSP_ZIP_PASSWORD != '' }}"
        run: echo "::set-output name=defined::true"
        env:
            KSP_ZIP_PASSWORD: ${{ secrets.KSP_ZIP_PASSWORD }}