name: Check Secret

on:
  workflow_call:
    inputs:
      blacklist_path:
        type: string
        required: False

jobs:
  validate-cfg:
    name: Validate Cfg-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: check out BuildTools
        uses: KSP-RO/BuildTools/checkout-BuildTools@master

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.0

      - name: disable blacklisted files
        # check if path is defined
        if: "${{ github.event.inputs.blacklist_path != '' }}"
        shell: bash
        run: python ${GITHUB_WORKSPACE}/BuildTools/.github/workflows/disableFiles.py ${GITHUB_WORKSPACE} ${{ inputs.blacklist_path }}

      - name: Validate config files
        uses: KSP-CKAN/KSPMMCfgParser@master
